#!/bin/bash
# Clean Desktop — generated by Desktop Cleaner install.sh.
# Double-click to tidy your Desktop into ~/Documents/Desktop.
# (To change behavior, edit the repo instead of this file, then re-run install.sh.)
exec "/Users/{...}/Documents/GitHub/Desktop Cleaner/bin/clean-desktop.sh"
