#!/bin/bash
#
# Desktop Cleaner — installer
# Builds a double-clickable "Clean Desktop.app" on your Desktop. Unlike a
# .command file, an app bundle runs its script directly — no Terminal window
# opens and nothing needs to be closed. The run happens silently in the
# background; a macOS notification reports the result, and full output is
# written to the run log.
#
# The app is a thin wrapper around bin/clean-desktop.sh in this repo, so edits
# here take effect immediately. If you *move this repo*, re-run ./install.sh.

set -u

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT="$REPO_DIR/bin/clean-desktop.sh"
DESKTOP="${DESKTOP_CLEANER_DESKTOP:-$HOME/Desktop}"
APP_NAME="Clean Desktop.app"
APP="$DESKTOP/$APP_NAME"
APP_EXE="$APP/Contents/MacOS/Clean Desktop"
SERVICES_DIR="${DESKTOP_CLEANER_SERVICES_DIR:-$HOME/Library/Services}"
WORKFLOW="$SERVICES_DIR/Clean Desktop.workflow"
MARKER="generated by Desktop Cleaner install.sh"
DEST_SHOW="${DESKTOP_CLEANER_DEST:-$HOME/Documents/Desktop}"

die() { echo "❌ $1"; exit 1; }

[ -f "$SCRIPT" ] || die "Cannot find $SCRIPT — run this from inside the repo."

chmod +x "$SCRIPT" || die "Could not make $SCRIPT executable."

# Replace a previously generated app; refuse to clobber anything we didn't make.
# -L catches a dangling symlink, which -e alone would miss.
if [ -e "$APP" ] || [ -L "$APP" ]; then
  if grep -q "$MARKER" "$APP_EXE" 2>/dev/null; then
    rm -rf "$APP"
  else
    die "$APP already exists and was not $MARKER — move it aside and re-run."
  fi
fi

# Retire the old Terminal-based launcher, if a previous version installed one.
OLD_LAUNCHER="$DESKTOP/Clean Desktop.command"
if [ -f "$OLD_LAUNCHER" ] && grep -q "$MARKER" "$OLD_LAUNCHER" 2>/dev/null; then
  rm -f "$OLD_LAUNCHER"
  echo "🧹 Removed old Terminal-based launcher: $OLD_LAUNCHER"
fi

mkdir -p "$APP/Contents/MacOS" || die "Could not create $APP — is the Desktop writable?"

cat > "$APP/Contents/Info.plist" <<'EOF' || die "Could not write Info.plist."
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleName</key>
	<string>Clean Desktop</string>
	<key>CFBundleDisplayName</key>
	<string>Clean Desktop</string>
	<key>CFBundleIdentifier</key>
	<string>com.desktop-cleaner.clean-desktop</string>
	<key>CFBundleExecutable</key>
	<string>Clean Desktop</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>2.0</string>
	<key>CFBundleVersion</key>
	<string>2.0</string>
	<key>LSUIElement</key>
	<true/>
	<key>LSMinimumSystemVersion</key>
	<string>11.0</string>
</dict>
</plist>
EOF

cat > "$APP_EXE" <<EOF || die "Could not write the app executable."
#!/bin/bash
# Clean Desktop — $MARKER.
# Runs the cleaner in the background: no window opens. Output is captured to
# the run log; a notification reports the result.
# (To change behavior, edit the repo instead of this file, then re-run install.sh.)
notify() {
  osascript -e "display notification \"\$1\" with title \"Desktop Cleaner\"" >/dev/null 2>&1 || true
}
DEST="\${DESKTOP_CLEANER_DEST:-\$HOME/Documents/Desktop}"
LOG_DIR="\$DEST"
mkdir -p "\$LOG_DIR" 2>/dev/null || LOG_DIR="\${TMPDIR:-/tmp}"
SCRIPT="$SCRIPT"
if [ ! -r "\$SCRIPT" ]; then
  # Repo moved/deleted, or macOS is blocking access to where it lives.
  notify "Can't read the Desktop Cleaner repo — moved, or access blocked? Re-run install.sh. Nothing moved."
  exit 1
fi
exec "\$SCRIPT" > "\$LOG_DIR/.last-run.txt" 2>&1
EOF

chmod +x "$APP_EXE" || die "Could not make the app executable runnable."
# Best-effort ad-hoc signature, and clear any quarantine flag so Gatekeeper
# won't block the double-click.
codesign --force -s - "$APP" >/dev/null 2>&1 || true
xattr -dr com.apple.quarantine "$APP" 2>/dev/null || true

# --- Finder Quick Action -----------------------------------------------------
# A Services workflow so "Clean Desktop" shows up when you right-click any
# item on the Desktop (Quick Actions submenu) and under Finder ▸ Services.
# It just launches the app in the background, so it shares the app's TCC
# permissions and logging. Same replace/refuse rules as the app.
if [ -e "$WORKFLOW" ] || [ -L "$WORKFLOW" ]; then
  if grep -q "$MARKER" "$WORKFLOW/Contents/document.wflow" 2>/dev/null; then
    rm -rf "$WORKFLOW"
  else
    die "$WORKFLOW already exists and was not $MARKER — move it aside and re-run."
  fi
fi

mkdir -p "$WORKFLOW/Contents" || die "Could not create $WORKFLOW."

cat > "$WORKFLOW/Contents/Info.plist" <<'EOF' || die "Could not write the Quick Action Info.plist."
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>NSServices</key>
	<array>
		<dict>
			<key>NSBackgroundColorName</key>
			<string>background</string>
			<key>NSIconName</key>
			<string>NSActionTemplate</string>
			<key>NSMenuItem</key>
			<dict>
				<key>default</key>
				<string>Clean Desktop</string>
			</dict>
			<key>NSMessage</key>
			<string>runWorkflowAsService</string>
			<key>NSRequiredContext</key>
			<dict>
				<key>NSApplicationIdentifier</key>
				<string>com.apple.finder</string>
			</dict>
			<key>NSSendFileTypes</key>
			<array>
				<string>public.item</string>
			</array>
		</dict>
	</array>
</dict>
</plist>
EOF

cat > "$WORKFLOW/Contents/document.wflow" <<EOF || die "Could not write the Quick Action document."
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>AMApplicationBuild</key>
	<string>512</string>
	<key>AMApplicationVersion</key>
	<string>2.10</string>
	<key>AMDocumentVersion</key>
	<string>2</string>
	<key>actions</key>
	<array>
		<dict>
			<key>action</key>
			<dict>
				<key>AMAccepts</key>
				<dict>
					<key>Container</key>
					<string>List</string>
					<key>Optional</key>
					<true/>
					<key>Types</key>
					<array>
						<string>com.apple.cocoa.string</string>
					</array>
				</dict>
				<key>AMActionVersion</key>
				<string>2.0.3</string>
				<key>AMApplication</key>
				<array>
					<string>Automator</string>
				</array>
				<key>AMParameterProperties</key>
				<dict>
					<key>COMMAND_STRING</key>
					<dict/>
					<key>CheckedForUserDefaultShell</key>
					<dict/>
					<key>inputMethod</key>
					<dict/>
					<key>shell</key>
					<dict/>
					<key>source</key>
					<dict/>
				</dict>
				<key>AMProvides</key>
				<dict>
					<key>Container</key>
					<string>List</string>
					<key>Types</key>
					<array>
						<string>com.apple.cocoa.string</string>
					</array>
				</dict>
				<key>ActionBundlePath</key>
				<string>/System/Library/Automator/Run Shell Script.action</string>
				<key>ActionName</key>
				<string>Run Shell Script</string>
				<key>ActionParameters</key>
				<dict>
					<key>COMMAND_STRING</key>
					<string># Clean Desktop — $MARKER.
APP="$APP"
if [ -d "\$APP" ]; then
  open -g "\$APP"
else
  osascript -e 'display notification "Clean Desktop.app not found on the Desktop — re-run install.sh from the Desktop Cleaner repo. Nothing moved." with title "Desktop Cleaner"'
fi</string>
					<key>CheckedForUserDefaultShell</key>
					<true/>
					<key>inputMethod</key>
					<integer>1</integer>
					<key>shell</key>
					<string>/bin/bash</string>
					<key>source</key>
					<string></string>
				</dict>
				<key>BundleIdentifier</key>
				<string>com.apple.RunShellScript</string>
				<key>CFBundleVersion</key>
				<string>2.0.3</string>
				<key>CanShowSelectedItemsWhenRun</key>
				<false/>
				<key>CanShowWhenRun</key>
				<true/>
				<key>Category</key>
				<array>
					<string>AMCategoryUtilities</string>
				</array>
				<key>Class Name</key>
				<string>RunShellScriptAction</string>
				<key>InputUUID</key>
				<string>4E7A1C22-6B3D-4A55-9E01-2C8F5D7A9B10</string>
				<key>Keywords</key>
				<array>
					<string>Shell</string>
					<string>Script</string>
					<string>Command</string>
					<string>Run</string>
					<string>Unix</string>
				</array>
				<key>OutputUUID</key>
				<string>6F9B2D34-8C5E-4B77-A123-3D9A6E8B0C21</string>
				<key>UUID</key>
				<string>8A1C3E46-AD7F-4C99-B345-4E0B7F9C1D32</string>
				<key>UnlocalizedApplications</key>
				<array>
					<string>Automator</string>
				</array>
				<key>arguments</key>
				<dict>
					<key>0</key>
					<dict>
						<key>default value</key>
						<integer>0</integer>
						<key>name</key>
						<string>inputMethod</string>
						<key>required</key>
						<string>0</string>
						<key>type</key>
						<string>0</string>
						<key>uuid</key>
						<string>0</string>
					</dict>
					<key>1</key>
					<dict>
						<key>default value</key>
						<false/>
						<key>name</key>
						<string>CheckedForUserDefaultShell</string>
						<key>required</key>
						<string>0</string>
						<key>type</key>
						<string>0</string>
						<key>uuid</key>
						<string>1</string>
					</dict>
					<key>2</key>
					<dict>
						<key>default value</key>
						<string></string>
						<key>name</key>
						<string>source</string>
						<key>required</key>
						<string>0</string>
						<key>type</key>
						<string>0</string>
						<key>uuid</key>
						<string>2</string>
					</dict>
					<key>3</key>
					<dict>
						<key>default value</key>
						<string></string>
						<key>name</key>
						<string>COMMAND_STRING</string>
						<key>required</key>
						<string>0</string>
						<key>type</key>
						<string>0</string>
						<key>uuid</key>
						<string>3</string>
					</dict>
					<key>4</key>
					<dict>
						<key>default value</key>
						<string>/bin/sh</string>
						<key>name</key>
						<string>shell</string>
						<key>required</key>
						<string>0</string>
						<key>type</key>
						<string>0</string>
						<key>uuid</key>
						<string>4</string>
					</dict>
				</dict>
				<key>conversionLabel</key>
				<integer>0</integer>
				<key>isViewVisible</key>
				<integer>1</integer>
				<key>location</key>
				<string>265.250000:305.000000</string>
				<key>nibPath</key>
				<string>/System/Library/Automator/Run Shell Script.action/Contents/Resources/Base.lproj/main.nib</string>
			</dict>
			<key>isViewVisible</key>
			<integer>1</integer>
		</dict>
	</array>
	<key>connectors</key>
	<dict/>
	<key>workflowMetaData</key>
	<dict>
		<key>applicationBundleIDsByPath</key>
		<dict>
			<key>/System/Library/CoreServices/Finder.app</key>
			<string>com.apple.finder</string>
		</dict>
		<key>applicationPaths</key>
		<array>
			<string>/System/Library/CoreServices/Finder.app</string>
		</array>
		<key>inputTypeIdentifier</key>
		<string>com.apple.Automator.fileSystemObject</string>
		<key>outputTypeIdentifier</key>
		<string>com.apple.Automator.nothing</string>
		<key>presentationMode</key>
		<integer>11</integer>
		<key>processesInput</key>
		<integer>0</integer>
		<key>serviceApplicationBundleID</key>
		<string>com.apple.finder</string>
		<key>serviceApplicationPath</key>
		<string>/System/Library/CoreServices/Finder.app</string>
		<key>serviceInputTypeIdentifier</key>
		<string>com.apple.Automator.fileSystemObject</string>
		<key>serviceOutputTypeIdentifier</key>
		<string>com.apple.Automator.nothing</string>
		<key>serviceProcessesInput</key>
		<integer>0</integer>
		<key>systemImageName</key>
		<string>NSActionTemplate</string>
		<key>useAutomaticInputType</key>
		<integer>0</integer>
		<key>workflowTypeIdentifier</key>
		<string>com.apple.Automator.servicesMenu</string>
	</dict>
</dict>
</plist>
EOF

# Nudge the services registry so the menu item appears without a re-login.
/System/Library/CoreServices/pbs -update 2>/dev/null || true

echo "✅ Installed: $APP"
echo "✅ Installed: $WORKFLOW (Finder Quick Action)"
echo
echo "Next:"
echo "  • Double-click \"Clean Desktop\" on your Desktop to clean up — or"
echo "    right-click any file on the Desktop ▸ Quick Actions ▸ Clean Desktop."
echo "  • No window opens — it runs in the background and posts a notification"
echo "    when done."
echo "  • Moved files land in: $DEST_SHOW"
echo "  • Full output of the latest run: $DEST_SHOW/.last-run.txt"
echo "    (history in $DEST_SHOW/.cleanup-log.txt)."
echo
echo "First-run macOS permissions:"
echo "  • macOS may ask \"Clean Desktop\" for permission to access your Desktop"
echo "    and Documents folders — click OK. If it never asks and the"
echo "    notification says it's blocked, grant it manually: System Settings ▸"
echo "    Privacy & Security ▸ Files & Folders (or Full Disk Access)."
