#!/bin/bash
#
# Desktop Cleaner — installer
# Builds a double-clickable "Clean Desktop.app" on your Desktop. Unlike a
# .command file, an app bundle runs its script directly — no Terminal window
# opens and nothing needs to be closed. The run happens silently in the
# background; a macOS notification reports the result, and full output is
# written to the run log.
#
# The app is a thin wrapper around bin/clean-desktop.sh in this repo, so edits
# here take effect immediately. If you *move this repo*, re-run ./install.sh.

set -u

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT="$REPO_DIR/bin/clean-desktop.sh"
DESKTOP="${DESKTOP_CLEANER_DESKTOP:-$HOME/Desktop}"
APP_NAME="Clean Desktop.app"
APP="$DESKTOP/$APP_NAME"
APP_EXE="$APP/Contents/MacOS/Clean Desktop"
MARKER="generated by Desktop Cleaner install.sh"
DEST_SHOW="${DESKTOP_CLEANER_DEST:-$HOME/Documents/Desktop}"

die() { echo "❌ $1"; exit 1; }

[ -f "$SCRIPT" ] || die "Cannot find $SCRIPT — run this from inside the repo."

chmod +x "$SCRIPT" || die "Could not make $SCRIPT executable."

# Replace a previously generated app; refuse to clobber anything we didn't make.
# -L catches a dangling symlink, which -e alone would miss.
if [ -e "$APP" ] || [ -L "$APP" ]; then
  if grep -q "$MARKER" "$APP_EXE" 2>/dev/null; then
    rm -rf "$APP"
  else
    die "$APP already exists and was not $MARKER — move it aside and re-run."
  fi
fi

# Retire the old Terminal-based launcher, if a previous version installed one.
OLD_LAUNCHER="$DESKTOP/Clean Desktop.command"
if [ -f "$OLD_LAUNCHER" ] && grep -q "$MARKER" "$OLD_LAUNCHER" 2>/dev/null; then
  rm -f "$OLD_LAUNCHER"
  echo "🧹 Removed old Terminal-based launcher: $OLD_LAUNCHER"
fi

mkdir -p "$APP/Contents/MacOS" || die "Could not create $APP — is the Desktop writable?"

cat > "$APP/Contents/Info.plist" <<'EOF' || die "Could not write Info.plist."
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleName</key>
	<string>Clean Desktop</string>
	<key>CFBundleDisplayName</key>
	<string>Clean Desktop</string>
	<key>CFBundleIdentifier</key>
	<string>com.desktop-cleaner.clean-desktop</string>
	<key>CFBundleExecutable</key>
	<string>Clean Desktop</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>2.0</string>
	<key>CFBundleVersion</key>
	<string>2.0</string>
	<key>LSUIElement</key>
	<true/>
	<key>LSMinimumSystemVersion</key>
	<string>11.0</string>
</dict>
</plist>
EOF

cat > "$APP_EXE" <<EOF || die "Could not write the app executable."
#!/bin/bash
# Clean Desktop — $MARKER.
# Runs the cleaner in the background: no window opens. Output is captured to
# the run log; a notification reports the result.
# (To change behavior, edit the repo instead of this file, then re-run install.sh.)
notify() {
  osascript -e "display notification \"\$1\" with title \"Desktop Cleaner\"" >/dev/null 2>&1 || true
}
DEST="\${DESKTOP_CLEANER_DEST:-\$HOME/Documents/Desktop}"
LOG_DIR="\$DEST"
mkdir -p "\$LOG_DIR" 2>/dev/null || LOG_DIR="\${TMPDIR:-/tmp}"
SCRIPT="$SCRIPT"
if [ ! -r "\$SCRIPT" ]; then
  # Repo moved/deleted, or macOS is blocking access to where it lives.
  notify "Can't read the Desktop Cleaner repo — moved, or access blocked? Re-run install.sh. Nothing moved."
  exit 1
fi
exec "\$SCRIPT" > "\$LOG_DIR/.last-run.txt" 2>&1
EOF

chmod +x "$APP_EXE" || die "Could not make the app executable runnable."
# Best-effort ad-hoc signature, and clear any quarantine flag so Gatekeeper
# won't block the double-click.
codesign --force -s - "$APP" >/dev/null 2>&1 || true
xattr -dr com.apple.quarantine "$APP" 2>/dev/null || true

echo "✅ Installed: $APP"
echo
echo "Next:"
echo "  • Double-click \"Clean Desktop\" on your Desktop to clean up."
echo "  • No window opens — it runs in the background and posts a notification"
echo "    when done."
echo "  • Moved files land in: $DEST_SHOW"
echo "  • Full output of the latest run: $DEST_SHOW/.last-run.txt"
echo "    (history in $DEST_SHOW/.cleanup-log.txt)."
echo
echo "First-run macOS permissions:"
echo "  • macOS may ask \"Clean Desktop\" for permission to access your Desktop"
echo "    and Documents folders — click OK. If it never asks and the"
echo "    notification says it's blocked, grant it manually: System Settings ▸"
echo "    Privacy & Security ▸ Files & Folders (or Full Disk Access)."
