#!/bin/bash
#
# Desktop Cleaner — installer
# Drops a double-clickable "Clean Desktop.command" onto your Desktop. The
# launcher is a thin wrapper that runs bin/clean-desktop.sh from this repo, so
# you can update the logic here without reinstalling.

set -u

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SCRIPT="$REPO_DIR/bin/clean-desktop.sh"
LAUNCHER_NAME="Clean Desktop.command"
DESKTOP="${DESKTOP_CLEANER_DESKTOP:-$HOME/Desktop}"
LAUNCHER="$DESKTOP/$LAUNCHER_NAME"

if [ ! -f "$SCRIPT" ]; then
  echo "❌ Cannot find $SCRIPT — run this from inside the repo."
  exit 1
fi

chmod +x "$SCRIPT"

cat > "$LAUNCHER" <<EOF
#!/bin/bash
# Clean Desktop — generated by Desktop Cleaner install.sh.
# Double-click to tidy your Desktop into ~/Documents/Desktop.
# (To change behavior, edit the repo instead of this file, then re-run install.sh.)
exec "$SCRIPT"
EOF

chmod +x "$LAUNCHER"
# Defensive: clear any quarantine flag so Gatekeeper won't block the double-click.
xattr -d com.apple.quarantine "$LAUNCHER" 2>/dev/null || true

echo "✅ Installed: $LAUNCHER"
echo
echo "Next:"
echo "  • Double-click \"$LAUNCHER_NAME\" on your Desktop to clean up."
echo "  • Moved files land in: ${DESKTOP_CLEANER_DEST:-$HOME/Documents/Desktop}"
echo
echo "First-run macOS permissions:"
echo "  • macOS may ask Terminal for permission to access your Desktop/Documents"
echo "    — click OK. If it never asks and the tool says it's blocked, grant it"
echo "    manually: System Settings ▸ Privacy & Security ▸ Files & Folders (or"
echo "    Full Disk Access) ▸ enable Terminal."
echo "  • If the window closes before you can read the summary, set Terminal ▸"
echo "    Settings ▸ Profiles ▸ Shell ▸ \"When the shell exits\" to \"Don't close\"."
echo "    (A summary is also saved to the log and shown as a notification.)"
